---
- hosts: '{{ provision_on | mandatory }}'
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: apt install python-setuptools
      apt: name=python-setuptools

    - name: apt install python-dev
      apt: name=python-dev

    - name: apt install python-pip
      apt: name=python-pip

    - name: pip install docker-py
      pip: name=docker-py version=1.1.0

